In [8]:
import pandas as pd

In [26]:
df = pd.DataFrame({
    "name":   ["Alice", "Bob", "Charlie", "Diana"],
    "age":    [25, None, 35, 28],
    "salary": [50000, 60000, None, 55000],
})

In [12]:
employees = pd.DataFrame({
    "name":       ["Alice", "Bob", "Charlie", "Diana"],
    "department": ["Engineering", "Marketing", "Engineering", "Finance"],
})

salaries = pd.DataFrame({
    "name":   ["Alice", "Bob", "Charlie", "Edward"],
    "salary": [50000, 60000, 70000, 80000],
})

In [4]:
merged = pd.merge(employees, salaries, on="name", how="left")

In [7]:
merged[merged["salary"].isna()]

    name department  salary
3  Diana    Finance     NaN

In [14]:
df.dropna()

    name   age   salary
0  Alice  25.0  50000.0
3  Diana  28.0  55000.0

In [15]:
df[["salary"]].fillna(df["salary"].mean())

    salary
0  50000.0
1  60000.0
2  55000.0
3  55000.0

In [16]:
df2 = pd.DataFrame({
    "date":        ["Mon", "Tue", "Wed", "Thu", "Fri"],
    "temperature": [30, None, None, 28, 29],
})

In [18]:
df2["temperature"].fillna(method="ffill")

C:\Users\rehan\AppData\Local\Temp\ipykernel_21304\1224568992.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2["temperature"].fillna(method="ffill")

0    30.0
1    30.0
2    30.0
3    28.0
4    29.0
Name: temperature, dtype: float64

In [19]:
df2["temperature"].fillna(method="bfill")

C:\Users\rehan\AppData\Local\Temp\ipykernel_21304\312734932.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2["temperature"].fillna(method="bfill")

0    30.0
1    28.0
2    28.0
3    28.0
4    29.0
Name: temperature, dtype: float64

In [ ]:
pd.merge(employees, salaries, on="name", how="outer")

In [ ]:
employees.merge(salaries, on="name", how="inner")

In [22]:
df[df["age"] == 25]

    name   age   salary
0  Alice  25.0  50000.0

In [23]:
df[(df["salary"] > 55000) & (df["age"] == 25)]

Empty DataFrame
Columns: [name, age, salary]
Index: []

In [ ]:
df[(df["salary"] > 55000) | (df["city"] == "NYC")]

In [27]:
df[df["age"] > 28][["name", "salary"]]

      name  salary
2  Charlie     NaN

In [ ]:
words = ["python", "data", "science", "job"]
dict_comprehension = {word: len(word) for word in words}
dict_comprehension

In [ ]:
df[df["age"] > 28]

In [ ]:
df["salary"].mean()

In [ ]:
df.groupby("city")[["age"]].max()

In [ ]:
df.groupby("city")[["salary"]].agg(["mean", "max", "min", "count"])

In [ ]:
result = df.groupby("city")[["salary"]].agg(["mean", "max", "min", "count"]).reset_index()
result

In [ ]:
def add_item(item, my_list=None):
    if my_list is None:
        my_list = []        # fresh list every call
    my_list.append(item)
    return my_list

print(add_item("apple"))   # ["apple"]
print(add_item("banana"))  # ["banana"]
print(add_item("cherry"))  # ["cherry"]

In [ ]:
def add_item(item, my_list=[]):
    my_list.append(item)
    return my_list

print(add_item("apple"))
print(add_item("banana"))
print(add_item("cherry"))

In [ ]:
#*args (Variable Positional Arguments)
def total(*numbers):
    print(numbers)
    return sum(numbers)

total(1, 2, 3)
total(10, 20, 30, 40, 50)

In [ ]:
#**kwargs (Variable Keyword Arguments)
def describe(**info):
    print(info)

describe(name="Alice", age=25, city="NYC")

In [ ]:
def apply_twice(func, value):
    return func(func(value))

def double(x):
    return x * 2

result = apply_twice(double, 4)
print(result)